######################
## Global variables ##
######################

samples: ["Day_4_L", "Day_4_R"]
stages: ["E7.5"]
celltypes: ["Epiblast", "Primitive_Streak", "Caudal_epiblast", "PGC", "Anterior_Primitive_Streak", "Notochord", "Def._endoderm", "Gut", "Nascent_mesoderm", "Mixed_mesoderm", "Intermediate_mesoderm", "Caudal_Mesoderm", "Paraxial_mesoderm", "Somitic_mesoderm", "Pharyngeal_mesoderm", "Cardiomyocytes", "Allantois", "ExE_mesoderm", "Mesenchyme", "Haematoendothelial_progenitors", "Endothelium", "Blood_progenitors_1", "Blood_progenitors_2", "Erythroid1", "Erythroid2", "Erythroid3", "NMP", "Rostral_neurectoderm", "Caudal_neurectoderm", "Neural_crest", "Forebrain_Midbrain_Hindbrain", "Spinal_cord", "Surface_ectoderm", "Visceral_endoderm", "ExE_endoderm", "ExE_ectoderm", "Parietal_endoderm"]
trajectories: ["Haemo","Mesen","HeaMen"]

#################
## Directories ##
#################

#directories:
#base: /home/lucas/Documents/Work/agrAnalysis
#original_data: /home/lucas/Documents/Work/agrAnalysis/data/original
#archr_directory: /home/lucas/Documents/Work/agrAnalysis/data/processed/atac/archR
#results: /home/lucas/Documents/Work/agrAnalysis/results/atac/archR

directories:
    base: /media/draco/lucask/chapter_three/agrAnalysis
    original_data: /media/draco/lucask/chapter_three/agrAnalysis/data/original
    archr_directory: /media/draco/lucask/chapter_three/agrAnalysis/data/processed/atac/archR
    results: /media/draco/lucask/chapter_three/agrAnalysis/results/atac/archR
    
#############
## Scripts ##
#############

scripts:
    # Basic processing
    create_arrow_files: ../processing/0_create_arrow_files.R
    create_archr_project: ../processing/1_create_archR_project.R
    create_archr_metadata: ../processing/2_create_archR_metadata.R
    qc_archr: ../processing/3_qc.R
    save_atac_matrices: ../processing/save_atac_matrices.R
    save_atac_anndata: ../processing/save_atac_anndata.R

    # Gene scores
    add_gene_scores: ../gene_scores/add_GeneScore_matrices.R
    gene_scores: ../gene_scores/add_GeneScore_matrices.R

    # Pseudobulk
    add_group_coverage: ../pseudobulk/1_archR_add_GroupCoverage.R
    pseudobulk: ../pseudobulk/2_archR_pseudobulk.R
    pseudobulk_with_replicates: ../pseudobulk/archR_pseudobulk_with_replicates.R

    # Peak calling
    peak_calling: ../peak_calling/peak_calling_archR.R
    plot_peak_calling_stats: ../peak_calling/analysis/plot_peak_calling_stats_archR.R
    link_peaks_to_genes: ../peak_calling/analysis/link_peaks2genes_genomic_distance.R

    # Export bigwig files
    create_bigwigs: ../bigwig/archR_export_bw.R

    # TF motif annotations
    add_motif_annotation: ../add_motif_annotation/archR_add_motif_annotation.R
    add_motif_annotation_manual: ../add_motif_annotation/add_motif_annotation_manual.R
    plot_motif_sequence_logo: ../add_motif_annotation/plot_motif_seqlogo.R

    # Metacells
    aggregate_atac_metacells: ../metacells/aggregate_atac_metacell.R

    # dimensionality reduction
    dimensionality_reduction_cells: ../dimensionality_reduction/cells/atac_dimensionality_reduction_cells.R
    dimensionality_reduction_metacells: ../dimensionality_reduction/metacells/atac_dimensionality_reduction_metacells.R

    # differential accessibility between cell types
    differential_cells: ../differential/cells/archr_differential_accessibility_cells.R
    differential_metacells: ../differential/metacells/differential_accessibility_metacells.R
    differential_celltype_pseudobulk: ../differential/pseudobulk/celltype/differential_accessibility_pseudobulk.R

    # differential accessibility between genotypes
    # differential_cells_genotype: ../differential/cells/genotype/run_diff_acc_genotype.R
    # differential_metacells_genotype: ../differential/metacells/genotype/run_diff_acc_genotype_metacells.R
    differential_celltype_genotype_pseudobulk: ../differential/pseudobulk/celltype_genotype/differential_accessibility_celltype_genotype_pseudobulk.R

    # Parse differential accessibility results
    parse_differential_celltype_cells: ../differential/cells/celltype/parse_differential_results.R
    parse_differential_celltype_metacells: ../differential/metacells/celltype/parse_differential_results.R
    parse_differential_celltype_pseudobulk: ../differential/pseudobulk/celltype/parse_differential_results.R
    parse_differential_celltype_genotype_pseudobulk: ../differential/pseudobulk/celltype_genotype/parse_differential_results.R

    # Define marker features
    define_markers_pseudobulk: ../differential/pseudobulk/celltype/analysis/define_markers.R

    # Celltype assignment
    celltype_assignment: ../celltype_assignment/archR_celltype_assignment.R

    # chromVAR
    background_peaks: ../add_motif_annotation/archR_add_background_peaks.R
    run_chromvar_cells: ../chromvar/cells/run_chromvar_from_archR.R
    run_chromvar_pseudobulk: ../chromvar/pseudobulk/run_chromvar_pseudobulk.R
    compare_chromvar_pseudobulk: ../chromvar/pseudobulk/compare_chromvar_results_pseudobulk.R

    # Feature stats
    calculate_feature_stats: ../feature_stats/archR_calculate_feature_stats.R


###############
## Resources ##
###############
#/media/draco/lucask/chapter_three
#resources:
    #genome: mm10
    #gene_metadata: /home/lucas/Documents/Work/agrAnalysis/Mmusculus_genes_BioMart.87.txt
    #cell_metadata: /home/lucas/Documents/Work/agrAnalysis/results/rna/mapping/sample_metadata_after_mapping.txt.gz
    #manual_motifs: /bi/group/reik/ricard/data/hg38_regulation/tf_motifs/jaspar # this one is a thing as well, where to get it
    #python: /home/lucas/mambaforge/envs/snakemake/bin/python

resources:
    genome: mm10
    gene_metadata: /media/draco/lucask/chapter_three/agrAnalysis/Mmusculus_genes_BioMart.87.txt
    cell_metadata: /media/draco/lucask/chapter_three/agrAnalysis/results/rna/mapping/sample_metadata_after_mapping.txt.gz
    manual_motifs: "/media/draco/lucask/chapter_three/agrAnalysis/JASPAR2022_CORE_vertebrates_non-redudant_pfms" # this one is a thing as well, where to get it
    python: /media/draco/lucask/mambaforge/envs/Renv/bin/python

################
## Parameters ##
################

create_arrow_files:
    min_fragments: 1000
    max_fragments: 1000000
    min_tss_score: 2.5

qc_archr:
    min_tss_enrichment: 9
    max_tss_enrichment: 35
    min_number_fragments: 3500
    max_number_fragments: 250000
    max_blacklist_ratio: 0.05

add_group_coverage:
    group_by: "celltype"
    min_cells: 100
    max_cells: 5000

peak_calling:
    group_by: "celltype"
    pathToMacs2: "/usr/local/bin/macs2" # on kolossus
    #pathToMacs2: "/home/lucas/.local/bin/macs3" #"/bi/group/reik/ricard/software/miniconda3/envs/main/bin/macs2"
    pvalue_cutoff: 0.001
    extend_summits: 300

create_bigwigs:
    group_by: ["celltype"]
    norm_method: "ReadsInTSS"
    tile_size: 100
    min_cells: 50

add_motif_annotation_manual:
    cutoff: 0.0001
    width: 7
    motif_annotation: ["JASPAR", "CISBP"]

aggregate_atac_metacells:
    min_frags: 200000
    matrices: ["PeakMatrix", "GeneScoreMatrix_TSS"]
    trajectories: ["Haemo","Mesen","HeaMen"]

dimensionality_reduction:
    matrix: "PeakMatrix"
    remove_ExE_cells: ["True", "False"]
    ndims: 50
    nfeatures: 25000
    umap_n_neighbors: 25
    umap_min_dist: 0.3
    batch_variable: ["sample","None"]
    batch_method: "MNN"
    colour_by: ["sample","stage","celltype","nFrags_atac","pass_rnaQC"]

dimensionality_reduction_metacells:
    matrix: "PeakMatrix"
    remove_ExE_cells: ["True", "False"]
    ndims: 50
    nfeatures: 25000
    umap_n_neighbors: 25
    umap_min_dist: 0.3
    batch_variable: ["sample","None"]
    batch_method: "MNN"
    colour_by: ["sample","stage","celltype","nFrags_atac"]

pseudobulk:
    group_by: ["celltype"]
    matrix: ["PeakMatrix", "GeneScoreMatrix_TSS"]

pseudobulk_with_replicates:
    nrep: 5
    min_cells: 25
    fraction_cells_per_replicate: 0.30

differential:
    group_variable: ["celltype"]
    # matrix: ["PeakMatrix", "GeneScoreMatrix_TSS"]
    matrix: ["PeakMatrix"]

differential_cells:
    min_cells: 25

differential_metacells:
    min_cells: 5

# differential_pseudobulk:
#     group_variable: ["celltype"]
#     matrix: ["PeakMatrix", "GeneScoreMatrix_TSS"]
#     min_cells: 50

celltype_assignment:
    k: 25
    input_celltype_column: "celltype"
    output_celltype_column: "celltype.predicted"

background_peaks:
    method: "chromVAR"
    number_background_peaks: 50

run_chromvar_pseudobulk:
    motif_annotation: ["JASPAR", "CISBP"]
    group_by: ["celltype"]
    min_peaks: 50

run_chromvar_cells:
    motif_annotation: ["JASPAR", "CISBP"]
    min_peaks: 50

link_peaks_to_genes:
    gene_window: 100000

calculate_feature_stats:
    group_by: ["celltype"]
    matrix: ["PeakMatrix", "GeneScoreMatrix_TSS"]


plot_motif_sequence_logo:
    motif_annotation: ["JASPAR", "CISBP"]

save_atac_matrices:
    matrices: ["PeakMatrix", "GeneScoreMatrix_TSS"]
    # matrices: ["PeakMatrix", "GeneScoreMatrix_TSS", "GeneScoreMatrix_distal"]

plot_peak_calling_stats:
    min_peak_score: 10

define_markers:
    min_fold_change: 1.0
    min_score: 0.85
    fdr: 0.01

###########
## Slurm ##
###########

slurm:  # memory in MB
    create_arrow_files: 
        threads: 4
        memory: 5000
    create_archr_project:
        threads: 4
        memory: 32000
    create_archr_metadata:
        threads: 8
        memory: 32000
    qc_archr: 
        threads: 4
        memory: 32000
    add_group_coverage:
        threads: 8
        memory: 32000
    add_gene_scores:
        threads: 4
        memory: 60000
    peak_calling:
        threads: 8
        memory: 60000
    create_bigwigs:
        threads: 8
        memory: 60000
    add_motif_annotation:
        threads: 1
        memory: 5000
    add_motif_annotation_manual:
        threads: 1
        memory: 10000
    dimensionality_reduction:
        threads: 1
        memory: 60000
    dimensionality_reduction_metacells:
        threads: 1
        memory: 60000
    dimensionality_reduction_per_stage:
        threads: 1
        memory: 60000
    pseudobulk:
        threads: 1
        memory: 60000
    pseudobulk_with_replicates:
        threads: 1
        memory: 60000
    celltype_assignment:
        threads: 1
        memory: 60000
    background_peaks:
        threads: 1
        memory: 60000
    run_chromvar_pseudobulk:
        threads: 1
        memory: 60000
    run_chromvar_cells:
        threads: 4
        memory: 60000
    compare_chromvar_pseudobulk:
        threads: 1
        memory: 60000
    link_peaks_to_genes:
        threads: 1
        memory: 60000
    calculate_feature_stats:
        threads: 1
        memory: 60000
    plot_motif_sequence_logo:
        threads: 1
        memory: 60000

    # Differential
    differential_cells:
        threads: 1
        memory: 5000
    differential_metacells:
        threads: 1
        memory: 9000
    differential_pseudobulk:
        threads: 1
        memory: 5000

    # Parse differential results
    parse_differential:
        threads: 1
        memory: 25000

    save_atac_matrices:
        threads: 1
        memory: 90000
    plot_peak_calling_stats:
        threads: 1
        memory: 60000
    aggregate_atac_metacells:
        threads: 1
        memory: 25000
    define_markers:
        threads: 1
        memory: 20000
    save_atac_anndata:
        threads: 1
        memory: 60000

